version: "3.8"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=https://vaultwarden.${SERVER_DOMAIN}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED:-false}
      - INVITATIONS_ALLOWED=${INVITATIONS_ALLOWED:-true}
      - SHOW_PASSWORD_HINT=${SHOW_PASSWORD_HINT:-false}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    security_opt:
      - no-new-privileges:true
    networks:
      - homeserver
    volumes:
      - /volume1/docker/vaultwarden:/data
    labels:
      - "my.zone=homeserver"
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.${SERVER_DOMAIN}`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls.certresolver=myresolver"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.docker.network=homeserver"

networks:
  homeserver:
    name: homeserver
    external: true
